const usuarios = [
    {
    first_name:"Jose",
    last_name:"Zurcom",
 	gender:"M",
 	n_document:"30772620",
 	email:"user@user.com",
    password:"Admin*7754", 
    phone:"3439323322",
    city:"Rosario",
    role:"User"
      },
      {
        first_name:"Yanina",
        last_name:"Zur",
         gender:"F",
         n_document:"39772620",
         email:"yani@Admin.com",
        password:"Admin*7754", 
        phone:"3439423322",
        city:"Rosario",
        role:"Admin"
      },
      {
        first_name:"Natalia",
        last_name:"Mendez",
         gender:"F",
         n_document:"40772620",
         email:"nati@Admin.com",
        password:"Admin*7754", 
        phone:"3439313322",
        city:"Rosario",
        role:"User"
      },
      {
        first_name:"Nicolas",
        last_name:"Ceri",
         gender:"M",
         n_document:"38772620",
         email:"nico@Admin.com",
        password:"Admin*7754", 
        phone:"343903322",
        city:"Rosario",
        role:"User"
      },
      {
        first_name:"Maria",
        last_name:"Ruiz",
         gender:"F",
         n_document:"31772620",
         email:"maria@Admin.com",
        password:"Admin*7754", 
        phone:"3439323922",
        city:"Rosario",
        role:"User"
      },
    
  ];
  
  module.exports = usuarios;